parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"aezc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Entity=void 0;class t{constructor(){this.id=null,this.components=[]}setID(t=""){return this.id=t,this}addComponent(t){return t.unique&&this.components.some(e=>e.name===t.name)?console.warn(`Attempting to add non-unique component "${t.name}" to "${this.id}" when that component already exists!`):this.components.push(t),this}removeComponents(t,e){return this.components=this.components.filter(n=>!(n.name===t&&e(n.state))),this}hasComponent(t){return this.components.some(e=>e.name===t)}getComponents(t){return this.components.filter(e=>e.name===t).map(t=>t.state)}}exports.Entity=t;
},{}],"tIyq":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Component=void 0;const e={Name:(e="")=>({name:"name",unique:!0,state:e}),Value:(e=0)=>({name:"value",unique:!0,state:e}),Level:(e=1,t=0)=>({name:"level",unique:!0,state:{level:e,exp:t}}),Equippable:e=>({name:"equippable",unique:!0,state:{slot:e}}),Attributes:(e=100)=>({name:"attributes",unique:!0,state:{health:e}}),Attacking:e=>({name:"attacking",unique:!1,state:e})};exports.Component=e;
},{}],"pkl2":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.System=void 0;const e={greet:e=>(e.filter(e=>e.hasComponent("name")).forEach(e=>console.log(`Hello ${e.getComponents("name")[0]}!`)),e),attack:e=>e.filterMap(e=>e.hasComponent("attacking"),t=>(t.getComponents("attacking").forEach(o=>e.filterMap(e=>e.id===o,e=>(e.getComponents("attributes")[0].health-=t.getComponents("level")[0].level,e))),t)),checkDead:e=>e.filterMap(e=>e.hasComponent("attributes")&&e.getComponents("attributes")[0].health<=0,t=>(e.filterMap(e=>e.hasComponent("attacking"),e=>e.removeComponents("attacking",e=>e===t.id)),t))};exports.System=e;
},{}],"es35":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.EntityList=void 0;var e=t(require("shortid"));function t(e){return e&&e.__esModule?e:{default:e}}class r extends Array{filterMap(e,t){return this.map(r=>e(r)?t(r):r)}push(t){return super.push(t.setID(e.default.generate())),this}}exports.EntityList=r;
},{}],"Kq7/":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Manager=void 0;var t=require("./entity"),e=require("./utils");class i{constructor(){return this.entityCount=0,this.entities=new e.EntityList,this.systems=[],this}addEntity(e=[]){return this.entities.push(e.reduce((t,e)=>t.addComponent(e),new t.Entity)),this}removeEntity(t){return this.entities=this.entities.filter(e=>e.id!==t),this}getEntities(){return this.entities}updateEntities(t,e){return this.entities=this.entities.filterMap(t,e),this}addSystem(t){return this.systems.push(t),this}runSystems(){return this.entities=this.systems.reduce((t,e)=>t=e(t),this.entities),this}}exports.Manager=i;
},{"./entity":"aezc","./utils":"es35"}],"LTnQ":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./entity"),t=require("./component"),r=require("./system"),n=require("./manager"),i=require("./utils"),o={Entity:e.Entity,Component:t.Component,System:r.System,Manager:n.Manager};exports.default=o;
},{"./entity":"aezc","./component":"tIyq","./system":"pkl2","./manager":"Kq7/","./utils":"es35"}],"epB2":[function(require,module,exports) {
"use strict";var e=a(require("express")),t=a(require("lowdb")),n=require("ws"),o=a(require("./ECS"));function a(e){return e&&e.__esModule?e:{default:e}}const d=process.env.PORT||3e3,s=(0,e.default)().listen(d,()=>{}),l=new n.Server({server:s}),u={};l.on("connection",e=>{e.on("message",e=>{console.log(e)}),e.on("close",()=>{})});const i=new o.default.Manager;i.addEntity([o.default.Component.Name("andy"),o.default.Component.Attributes(),o.default.Component.Level()]).addEntity([o.default.Component.Name("alex"),o.default.Component.Attributes(150),o.default.Component.Level(),o.default.Component.Attacking(i.getEntities().find(e=>"andy"===e.getComponents("name")[0]).id)]).updateEntities(e=>e.hasComponent("name")&&"andy"===e.getComponents("name")[0],e=>e.addComponent(o.default.Component.Attacking(i.getEntities().find(e=>"alex"===e.getComponents("name")[0]).id))).addSystem(o.default.System.attack).addSystem(o.default.System.checkDead);for(let m=0;m<=200;m++)i.runSystems();console.dir(i,{depth:null});
},{"./ECS":"LTnQ"}]},{},["epB2"], null)
//# sourceMappingURL=/main.map