parcelRequire=function(e,r,n,t){var i="function"==typeof parcelRequire&&parcelRequire,o="function"==typeof require&&require;function u(n,t){if(!r[n]){if(!e[n]){var f="function"==typeof parcelRequire&&parcelRequire;if(!t&&f)return f(n,!0);if(i)return i(n,!0);if(o&&"string"==typeof n)return o(n);var c=new Error("Cannot find module '"+n+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[n][1][r]||r},p.cache={};var l=r[n]=new u.Module(n);e[n][0].call(l.exports,p,l,l.exports,this)}return r[n].exports;function p(e){return u(p.resolve(e))}}u.isParcelRequire=!0,u.Module=function(e){this.id=e,this.bundle=u,this.exports={}},u.modules=e,u.cache=r,u.parent=i,u.register=function(r,n){e[r]=[function(e,r){r.exports=n},{}]};for(var f=0;f<n.length;f++)u(n[f]);if(n.length){var c=u(n[n.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=c:"function"==typeof define&&define.amd?define(function(){return c}):t&&(this[t]=c)}return u}({"aezc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Entity=void 0;class t{constructor(){this.id=null,this.components=[]}setID(t=""){return this.id=t,this}addComponent(t){return t.unique&&this.components.some(e=>e.name===t.name)?console.warn(`Attempting to add non-unique component "${t.name}" to "${this.id}" when that component already exists!`):this.components.push(t),this}removeComponents(t,e){return this.components=this.components.filter(n=>!(n.name===t&&e(n.state))),this}hasComponent(t){return this.components.some(e=>e.name===t)}getComponents(t){return this.components.filter(e=>e.name===t).map(t=>t.state)}}exports.Entity=t;
},{}],"tIyq":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Component=void 0;const e={Name:(e="")=>({name:"name",unique:!0,state:e}),Value:(e=0)=>({name:"value",unique:!0,state:e}),Level:(e=1,n=0)=>({name:"level",unique:!0,state:{level:e,exp:n}}),Equippable:(...e)=>({name:"equippable",unique:!0,state:{slotOptions:e}}),Inventory:(e=[])=>({name:"inventory",unique:!0,state:e}),Equipped:({head:e=null,back:n=null,torso:a=null,legs:t=null,hands:u=null,feet:l=null,mainhand:i=null,offhand:s=null,ring1:o=null,ring2:m=null}={})=>({name:"equipped",unique:!0,state:{head:e,back:n,torso:a,legs:t,hands:u,feet:l,mainhand:i,offhand:s,ring1:o,ring2:m}}),Damage:(e=0)=>({name:"damage",unique:!1,state:e}),DamageModifier:(e=0)=>({name:"damageModifier",unique:!1,state:e}),Attributes:(e=100)=>({name:"attributes",unique:!0,state:{health:e}}),Attacking:(e,n=0)=>({name:"attacking",unique:!1,state:{id:e,damage:n}})};exports.Component=e;
},{}],"pkl2":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.System=void 0;const t={attack:t=>t.mapIf(t=>t.hasComponent("attacking"),e=>(e.getComponents("attacking").forEach(e=>t.mapIf(t=>t.id===e.id,t=>(t.getComponents("attributes")[0].health-=e.damage,t))),e)),checkDead:t=>t.mapIf(t=>t.hasComponent("attributes")&&t.getComponents("attributes")[0].health<=0,e=>(e.removeComponents("attacking",t=>!0),t.mapIf(t=>t.hasComponent("attacking"),t=>t.removeComponents("attacking",t=>t===e.id)),e)),calculateDamage:t=>{t.filter(t=>t.hasComponent("attacking")),t.filter(t=>t.hasComponent("damageModifier"))}};exports.System=t;
},{}],"es35":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.EntityList=void 0;var e=t(require("shortid"));function t(e){return e&&e.__esModule?e:{default:e}}class r extends Array{mapIf(e,t){return this.map(r=>e(r)?t(r):r)}push(t){return super.push(t.setID(e.default.generate())),t}}exports.EntityList=r;
},{}],"Kq7/":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.Manager=void 0;var t=require("./entity"),e=require("./utils");class i{constructor(){return this.entityCount=0,this.entities=new e.EntityList,this.systems=[],this}addEntity(e=[]){return this.entities.push(e.reduce((t,e)=>t.addComponent(e),new t.Entity)).id}removeEntity(t){return this.entities=this.entities.filter(e=>e.id!==t),this}getEntities(){return this.entities}updateEntities(t,e){return this.entities=this.entities.mapIf(t,e),this}addSystem(t){return this.systems.push(t),this}runSystems(){return this.entities=this.systems.reduce((t,e)=>t=e(t),this.entities),this}}exports.Manager=i;
},{"./entity":"aezc","./utils":"es35"}],"LTnQ":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("./entity"),t=require("./component"),r=require("./system"),n=require("./manager"),i=require("./utils"),o={Entity:e.Entity,Component:t.Component,System:r.System,Manager:n.Manager};exports.default=o;
},{"./entity":"aezc","./component":"tIyq","./system":"pkl2","./manager":"Kq7/","./utils":"es35"}],"epB2":[function(require,module,exports) {
"use strict";var e=o(require("express")),n=o(require("lowdb")),t=require("ws"),a=o(require("./ECS"));function o(e){return e&&e.__esModule?e:{default:e}}const d=process.env.PORT||3e3,l=(0,e.default)().listen(d,()=>{}),m=new t.Server({server:l}),u={};m.on("connection",e=>{e.on("message",e=>{console.log(e)}),e.on("close",()=>{})});const p=new a.default.Manager,i=p.addEntity([a.default.Component.Name("sword"),a.default.Component.Value(10),a.default.Component.Equippable(["mainhand"],["offhand"]),a.default.Component.DamageModifier(5)]),f=p.addEntity([a.default.Component.Name("battleaxe"),a.default.Component.Value(10),a.default.Component.Equippable(["mainhand","offhand"]),a.default.Component.DamageModifier(8)]),s=p.addEntity([a.default.Component.Name("hoodedCloak"),a.default.Component.Value(8),a.default.Component.Equippable(["head","back"])]),C=p.addEntity([a.default.Component.Name("andy"),a.default.Component.Attributes(),a.default.Component.Level(),a.default.Component.Inventory(),a.default.Component.Equipped({mainhand:i})]),r=p.addEntity([a.default.Component.Name("alex"),a.default.Component.Attributes(150),a.default.Component.Level(),a.default.Component.Attacking(p.getEntities().find(e=>"andy"===e.getComponents("name")[0]).id,3),a.default.Component.Inventory(),a.default.Component.Equipped({mainhand:f,offhand:f})]);p.updateEntities(e=>e.hasComponent("name")&&"andy"===e.getComponents("name")[0],e=>e.addComponent(a.default.Component.Attacking(p.getEntities().find(e=>"alex"===e.getComponents("name")[0]).id,5))).addSystem(a.default.System.attack).addSystem(a.default.System.checkDead);for(let c=0;c<=200;c++)p.runSystems();console.dir(p,{depth:null});
},{"./ECS":"LTnQ"}]},{},["epB2"], null)
//# sourceMappingURL=/main.map